apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
      - name: app3
        image: python:3.11-slim
        command: ["python", "-m", "http.server", "80"]
        ports:
        - containerPort: 80
