Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu2004"
    # Shared folder for all VMs
    config.vm.synced_folder "/home/riri/iot/p2", "/home/vagrant/p2",
        type: "nfs", mount_options: ['vers=3', 'tcp']

    # Define Server machine
    config.vm.define "rchboukiS" do |server|
        server.vm.hostname = "rchboukiS"
        server.vm.network "private_network", ip: "192.168.56.110"
        server.vm.provider "libvirt" do |vb|
            vb.memory = "512"
            vb.cpus = 1
        end

        # Provision script for K3s server
        server.vm.provision "shell", path: "scripts/server.sh"
    end
end

