Vagrant.configure("2") do |config|
    # Shared folder for all VMs
    config.vm.box = "generic/ubuntu2004"
    config.vm.synced_folder "/home/riri/iot/p1_riri", "/home/vagrant/p1",
        type: "nfs", mount_options: ['vers=3', 'tcp']

    # Define first machine (Server)
    config.vm.define "rchboukiS" do |server|
        server.vm.hostname = "rchboukiS"
        server.vm.network "private_network", ip: "192.168.56.110"
        server.vm.provider "libvirt" do |vb|
            vb.memory = "512"
            vb.cpus = 1
        end

        # Provision script for K3s server
        server.vm.provision "shell", path: "scripts/server.sh"
    end

    # Define second machine (ServerWorker)
    config.vm.define "thibnguySW" do |worker|
        worker.vm.hostname = "thibnguySW"
        worker.vm.network "private_network", ip: "192.168.56.111"
        worker.vm.provider "libvirt" do |vb|
            vb.memory = "1024"
            vb.cpus = 1
        end

        worker.vm.provision "shell", path: "scripts/worker.sh"
    end

end

