Vagrant.configure("2") do |config|
  
  # Define first machine (Server)
  config.vm.define "rchboukiS" do |server|
    server.vm.box = "generic/ubuntu2310"
    server.vm.hostname = "rchboukiS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "libvirt" do |vb|
      vb.memory = "512"
      vb.cpus = 1
    end
    # SSH setup is automatic in Vagrant
  end

  # Define second machine (ServerWorker)
  config.vm.define "rchboukiSW" do |worker|
    worker.vm.box = "generic/ubuntu2310"
    worker.vm.hostname = "rchboukiSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "libvirt" do |vb|
      vb.memory = "512"
      vb.cpus = 1
    end
  end

end

